name: API workflow

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
      - uses: actions/checkout@v1
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install coverage
        run: pip install pytest-cov
      - name: Run tests and collect coverage
        working-directory: ./bpllib
        run: pytest --cov .  # should consider to include experiments?
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./bpllib/coverage.xml
          fail_ci_if_error: true
